env:
  browser: true
  es2021: true
extends:
  - airbnb
  - prettier
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/typescript'
  - 'plugin:import/warnings'
  - 'plugin:react/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
  - '@typescript-eslint'
rules:
  {
    'import/extensions':
      ['error', 'ignorePackages', { 'ts': 'never', 'tsx': 'never' }],
    'no-use-before-define': 'off',
    'react/jsx-filename-extension': ['warn', { 'extensions': ['.tsx'] }],
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-use-before-define': ['error'],
  }
